<?php

/**
 * RBAC matrix: roles → permission keys (module.action).
 * Wildcard: '*' => true grants all keys for that role.
 *
 * @see \App\Services\UserRbacService Policies use effective permissions from this matrix.
 */
return [

    'permission_admin_roles' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('PPMS_RBAC_ADMIN_ROLES', 'admin'))
    ))),

    'modules' => [
        'users' => ['label' => 'Users'],
        'dashboard' => ['label' => 'Dashboard'],
        'projects' => ['label' => 'Projects'],
        'kpi' => ['label' => 'KPI'],
        'teams' => ['label' => 'Teams'],
        'reports' => ['label' => 'Reports'],
        'vendors' => ['label' => 'Vendors'],
        'contracts' => ['label' => 'Contracts'],
        'kaizens' => ['label' => 'Kaizen'],
        'innovation' => ['label' => 'Innovation'],
        'evaluations' => ['label' => 'Evaluations'],
        'notifications' => ['label' => 'Notifications'],
    ],

    'actions' => ['view', 'create', 'update', 'delete'],

    /*
    |--------------------------------------------------------------------------
    | Role → permissions (explicit keys; omit = denied unless wildcard)
    |--------------------------------------------------------------------------
    */
    'roles' => [
        'admin' => [
            '*' => true,
        ],
        'pm' => [
            'users.view' => true,
            'dashboard.view' => true,
            'projects.view' => true,
            'projects.create' => true,
            'projects.update' => true,
            'projects.delete' => true,
            'kpi.view' => true,
            'teams.view' => true,
            'teams.create' => true,
            'teams.update' => true,
            'teams.delete' => true,
            'reports.view' => true,
            'reports.create' => true,
            'reports.update' => true,
            'reports.delete' => true,
            'vendors.view' => true,
            'vendors.create' => true,
            'vendors.update' => true,
            'vendors.delete' => true,
            'contracts.view' => true,
            'contracts.create' => true,
            'contracts.update' => true,
            'contracts.delete' => true,
            'kaizens.view' => true,
            'kaizens.create' => true,
            'kaizens.update' => true,
            'kaizens.delete' => true,
            'innovation.view' => true,
            'innovation.create' => true,
            'innovation.update' => true,
            'innovation.delete' => true,
            'evaluations.view' => true,
            'evaluations.create' => true,
            'evaluations.update' => true,
            'evaluations.delete' => true,
            'notifications.view' => true,
            'notifications.create' => true,
            'notifications.update' => true,
            'notifications.delete' => true,
        ],
        'tl' => [
            'users.view' => true,
            'dashboard.view' => true,
            'projects.view' => true,
            'projects.create' => true,
            'projects.update' => true,
            'projects.delete' => false,
            'kpi.view' => true,
            'teams.view' => true,
            'teams.create' => true,
            'teams.update' => true,
            'teams.delete' => false,
            'reports.view' => true,
            'reports.create' => true,
            'reports.update' => true,
            'reports.delete' => false,
            'vendors.view' => true,
            'vendors.create' => true,
            'vendors.update' => true,
            'vendors.delete' => true,
            'contracts.view' => true,
            'contracts.create' => true,
            'contracts.update' => true,
            'contracts.delete' => false,
            'kaizens.view' => true,
            'kaizens.create' => true,
            'kaizens.update' => true,
            'kaizens.delete' => false,
            'innovation.view' => true,
            'innovation.create' => true,
            'innovation.update' => true,
            'innovation.delete' => false,
            'evaluations.view' => true,
            'evaluations.create' => true,
            'evaluations.update' => true,
            'evaluations.delete' => false,
            'notifications.view' => true,
            'notifications.create' => true,
            'notifications.update' => true,
            'notifications.delete' => false,
        ],
        'hr' => [
            'users.view' => true,
            'users.update' => true,
            'dashboard.view' => true,
            'projects.view' => true,
            'projects.create' => false,
            'projects.update' => false,
            'projects.delete' => false,
            'kpi.view' => true,
            'teams.view' => true,
            'teams.create' => false,
            'teams.update' => false,
            'teams.delete' => false,
            'reports.view' => true,
            'reports.create' => false,
            'reports.update' => true,
            'reports.delete' => false,
            'vendors.view' => true,
            'vendors.create' => false,
            'vendors.update' => false,
            'vendors.delete' => false,
            'contracts.view' => true,
            'contracts.create' => false,
            'contracts.update' => false,
            'contracts.delete' => false,
            'kaizens.view' => true,
            'kaizens.create' => true,
            'kaizens.update' => true,
            'kaizens.delete' => false,
            'innovation.view' => true,
            'innovation.create' => false,
            'innovation.update' => false,
            'innovation.delete' => false,
            'evaluations.view' => true,
            'evaluations.create' => true,
            'evaluations.update' => true,
            'evaluations.delete' => false,
            'notifications.view' => true,
            'notifications.create' => true,
            'notifications.update' => true,
            'notifications.delete' => false,
        ],
        'developer' => [
            'dashboard.view' => true,
            'projects.view' => true,
            'projects.create' => true,
            'projects.update' => false,
            'projects.delete' => false,
            'kpi.view' => true,
            'teams.view' => true,
            'teams.create' => false,
            'teams.update' => false,
            'teams.delete' => false,
            'reports.view' => true,
            'reports.create' => false,
            'reports.update' => false,
            'reports.delete' => false,
            'vendors.view' => true,
            'vendors.create' => true,
            'vendors.update' => true,
            'vendors.delete' => false,
            'contracts.view' => true,
            'contracts.create' => true,
            'contracts.update' => true,
            'contracts.delete' => false,
            'kaizens.view' => true,
            'kaizens.create' => true,
            'kaizens.update' => true,
            'kaizens.delete' => false,
            'innovation.view' => true,
            'innovation.create' => true,
            'innovation.update' => true,
            'innovation.delete' => false,
            'evaluations.view' => true,
            'evaluations.create' => false,
            'evaluations.update' => false,
            'evaluations.delete' => false,
            'notifications.view' => true,
            'notifications.create' => true,
            'notifications.update' => true,
            'notifications.delete' => false,
        ],
    ],

];
